### ISSUE TITLE
Demo 朋友圈 内存暴增

### ISSUE THREAD

**Issue by HaoXuan1988** [waynezxcv/Gallop#10]
Demo 里在朋友圈页面, 从头至尾, 反复,快速滑动, 内存暴增以至于闪退;

2016-07-04 13:52:52.957 LWAsyncDisplayViewDemo[1464:190384] Received memory warning.

求大神指点........

**Comment by waynezxcv** [comment]
你好。能说下具体怎么操作的么，是使用真机还是模拟器。我刚反复，快速滑动了3分钟，没有出现你说的情况。内存的消耗基本保持在一个范围内。不过用Instruments测试是有两个CoreText的API忘记释放内存了，之后会修复这个问题。但是没有出现内存暴增以至于闪退的情况。
![debug1](https://cloud.githubusercontent.com/assets/8408918/16553018/0f4dfc52-41f8-11e6-8fc5-840495729374.png)

**Comment by HaoXuan1988** [comment]
我用的真机 iPhone6P iOS 9.3.1  没敢太快的划.....每一次高峰都是我动作快了一点..
<img width="1022" alt="2016-07-04 5 26 01" src="https://cloud.githubusercontent.com/assets/15133696/16556452/b015c962-420c-11e6-985a-9029ae10db1b.png">

**Comment by waynezxcv** [comment]
你把Demo里面CellLayout.m的生成的内容图片和website类型的imageStorage的“imageStorage.needRerendering = YES;”这个行去掉，然后设置“imageStorage.clipsToBounds = YES;”内存占用应该会减小三分之二左右。
应该就不会出现那个问题了。在iPhone6上占用20M左右，6s上应该是40多M。

之前coretext有个ctframeref没有释放的问题也修复了，稍后更新一下。 ：）
用instrunments测试没有出现内存泄露的问题。

**Comment by waynezxcv** [comment]
@HaoXuan1988 已更新。
