### ISSUE TITLE
文本的点击事件响应问题

### ISSUE THREAD

**Issue by keyjacky** [waynezxcv/Gallop#11]
如果不是点击，单纯用手指在屏幕扫过带点击事件的文字区域，其点击事件方法仍然会响应，这个行为不太合理。比方说coretextdemo中顶部那段文字就能很容易重现这个问题

**Comment by waynezxcv** [comment]
确实。我修改一下

**Comment by waynezxcv** [comment]
已修改

**Comment by keyjacky** [comment]
還有個問題，按住带点击事件的文字区域（此區域此時變成高亮），此時手指不離開屏幕滑動到此文字區域外面（此時高亮消失），鬆開手指，點擊事件方法依然會相應，這個行為也不太合理

**Comment by waynezxcv** [comment]
近期修复。

**Comment by waynezxcv** [comment]
已修复。
