### ISSUE TITLE
如何在每个cell里插入自定义的控件

### ISSUE THREAD

**Issue by XHTeng** [waynezxcv/Gallop#13]
您好 麻烦问下  现在的结构cell里只能插入html解析后的数据，要是在cell当中插入一个自定义的控件该如何实现 就比如知乎的头部  放在了文章的某一个地方 现在的需求是要在文章结尾加入复杂控件的广告

**Comment by waynezxcv** [comment]
如果是插入文字或者图片，自己创建LWTextStorage或者LWImageStorage，然后在LWHTMLLayout的数组中，将创建的LWTextStorage或者LWImageStorage对象插入到指定位置就好了。若是其它类型的控件可以计算出位置frame，同时在解析HTML时，生成的storage通过设置EdigeInsets预留出空白的地方，然后add到htmlView上。

**Comment by XHTeng** [comment]
感谢您！
