### ISSUE TITLE
LWTextStorage可否限制行数

### ISSUE THREAD

**Issue by a6721879** [waynezxcv/Gallop#14]
我限制3行，超过3行，省略号代替

**Comment by waynezxcv** [comment]
目前不能直接设置行数限制 。但是可以通过文字的高度来限制，可以看看里面微信朋友圈的Demo，做了折叠文字和展开文字。

**Comment by waynezxcv** [comment]
之后加上限制行数功能。

**Comment by a6721879** [comment]
好的，加上的时候，艾特一下  = =。谢谢

**Comment by a6721879** [comment]
文字的高度来限制后，末尾能否加上省略号呢 - -

**Comment by a6721879** [comment]
目前的版本

**Comment by waynezxcv** [comment]
- -，手动加吧...

**Comment by a6721879** [comment]
= =。好吧

**Comment by a6721879** [comment]
这一条该提上日程了 －－。试着改，写不了

**Comment by a6721879** [comment]
大神，行数限制，我写完了

**Comment by waynezxcv** [comment]
LWTextStorage添加了一个属性maxNumberOfLines可以设置最大行数。

**Comment by hao1993** [comment]
您好，想问下最后有实现吗？ maxNumberOfLines = 2，同时希望文字显示不下的时候，   ...  代替
