### ISSUE TITLE
下拉刷新数据的时候，存在界面闪烁的问题

### ISSUE THREAD

**Issue by a6721879** [waynezxcv/Gallop#16]
能不能闪烁的平滑一些啊- -强迫症伤不起

**Comment by waynezxcv** [comment]
由于是异步绘制的，所以闪烁是避免不了的，因为有个绘制的过程。
闪烁平滑的话，可以试试使用类似
    [self.tableView beginUpdates];
    [self.tableView reloadSections:[NSIndexSet indexSetWithIndex:0]
                  withRowAnimation:UITableViewRowAnimationFade];
    [self.tableView endUpdates];
来替代
 [self.tableView reloadData];
应该会好很多。

如果是刷新单个Cell，可以采用截图之后创建一个UIImageView覆盖在上面，然后刷新完再把UIImageView移除的方法。

@a6721879

**Comment by waynezxcv** [comment]
由于是异步绘制的，所以闪烁是避免不了的，因为有个绘制的过程。
闪烁平滑的话，可以试试使用类似
    [self.tableView beginUpdates];
    [self.tableView reloadSections:[NSIndexSet indexSetWithIndex:0]
                  withRowAnimation:UITableViewRowAnimationFade];
    [self.tableView endUpdates];
来替代
 [self.tableView reloadData];
应该会好很多。

如果是刷新单个Cell，可以采用截图之后创建一个UIImageView覆盖在上面，然后刷新完再把UIImageView移除的方法。

@a6721879

**Comment by waynezxcv** [comment]
由于是异步绘制的，所以闪烁是避免不了的，因为有个绘制的过程。
闪烁平滑的话，可以试试使用类似
    [self.tableView beginUpdates];
    [self.tableView reloadSections:[NSIndexSet indexSetWithIndex:0]
                  withRowAnimation:UITableViewRowAnimationFade];
    [self.tableView endUpdates];
来替代
 [self.tableView reloadData];
应该会好很多。

如果是刷新单个Cell，可以采用截图之后创建一个UIImageView覆盖在上面，然后刷新完再把UIImageView移除的方法。

@a6721879

**Comment by a6721879** [comment]
这个方法也有一些问题，刷新多次，某一个cell会先闪烁一下其他的cell内容，然后再恢复正常显示自己的内容。 - -！

**Comment by waynezxcv** [comment]
下载一个最新版本的试试。。应该不会了 =。 = 现在会先将绘制的内容清空来的

**Comment by a6721879** [comment]
大神，你是在哪个类里面写的清空方法

**Comment by a6721879** [comment]
效果不如之前的 - -。请问大神，你是哪里写的清空方法，我学习下

**Comment by a6721879** [comment]
CGImageRef imageRef = (__bridge_retained CGImageRef)(self.contents);
    id contents = self.contents;
    self.contents = nil;
    if (imageRef) {
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_LOW, 0), ^{
            [contents class];
            CFRelease(imageRef);
        });
    }


是这一段话么

**Comment by a6721879** [comment]
图片闪烁的问题，我解决了，
LWImageStorage类 ---------
[self.layer lw_setImageWithURL:(NSURL *)imageStorage.contents
                  placeholderImage:imageStorage.placeholder
                      cornerRadius:imageStorage.cornerRadius
                              size:imageStorage.frame.size
                           options:SDWebImageTransformAnimatedImage progress:nil
                         completed:^(UIImage *image,
                                     NSError *error,
                                     SDImageCacheType cacheType,
                                     NSURL *imageURL) 


修改 options:SDWebImageTransformAnimatedImage，换成这个就不会闪烁了，不知道大神，你看法是什么

**Comment by waynezxcv** [comment]
额。你把这个换成除了SDWebImageAvoidAutoSetImage之外的任意一个都不会闪烁，而且建议你如果这么改就把completed那个回调的代码删除掉，否则会对同一张图片赋值两次。这么替换就放弃了观察runloop在合适时机对layer.contents赋值的机制了，对滚动流畅性有一定影响。不过能满足你的需求就好。

**Comment by a6721879** [comment]
好的，谢谢指点啊
