### ISSUE TITLE
长方形图片 设置 cornerRadius 变形

### ISSUE THREAD

**Issue by JamhonyZ** [waynezxcv/Gallop#19]
我在一个长方形图片上设置 cornerRadius ，数值要到一定量之后才会有剪切的效果，而且还是变形的，并非圆角切图，这个有办法优化么

**Comment by waynezxcv** [comment]
没太明白什么意思..是要切成圆形吗？长方形的图片你可以把UIImageView或者LWImageStorage.frame.bounds设置成正方形的.
