### ISSUE TITLE
求助，发送视频Video怎么实现。 

### ISSUE THREAD

**Issue by a289458845** [waynezxcv/Gallop#21]
如何在LWAsyncDisplayView 这个视图上给他添加一个自定义的View。 用来播放视频

**Comment by waynezxcv** [comment]
直接创建自定义的View，然后addSubView，添加到指定的View上

**Comment by a289458845** [comment]
在哪个视图添加呢，  我在自动布局的那个layout里面添加不上去。能加你qq问下吗。我这个很急

**Comment by a289458845** [comment]
我想自定义一个 和 LWTextStorage  平级的类型，  他提供的3种类型都不能自定义view。   所以我想在上面添加一个view， 上面添加播放器

**Comment by waynezxcv** [comment]
LWTextStorage只是数据模型，并不是实际的View对象。添加播放器的话，你需要创建自定义的View，然后addSubView，添加到指定的View上。然后继承LWLayout，自定义一个类把需要的数据作为这个类的属性，比如播放器的位置、URL等。然后在赋值的时候，写自定义的赋值规则。

**Comment by waynezxcv** [comment]
这么说吧，你把LWAsyncDisplayView看做一个UILabel。然后其他你该怎么写还是怎么写。

**Comment by a289458845** [comment]
现在的问题就是不知道怎么在布局的那个方法里拿到LWAsyncDisplayView ， 然后addsubview啊。。愁死我了

**Comment by a289458845** [comment]
<img width="1081" alt="default" src="https://cloud.githubusercontent.com/assets/20734274/18432185/42f9c37c-7913-11e6-879d-4c9c22df2500.png">  

我现在就是想在你的demo里面添加一个video， 因为这个框架是已经自动布局的。所以我准备添加一个view上去就搞定了呀。
