### ISSUE TITLE
LWTextStorage 文本如果含有emoji 会出现行距变大

### ISSUE THREAD

**Issue by coolyue** [waynezxcv/Gallop#28]
如何解决这个问题呢？

**Comment by waynezxcv** [comment]
emoji应该不会吧？是不是自定义添加的图片？如果是的话，可以把图片尺寸调小。

**Comment by errorUserInfo** [comment]
用苹果的emoji表情行间距就会变大

**Comment by errorUserInfo** [comment]
如何固定行高，我之前用YYText的YYTextLinePositionSimpleModifier的fixedLineHeight属性可以固定行高，就解决了问题，你这个库有没有相关的属性
