### ISSUE TITLE
你好 崩溃

### ISSUE THREAD

**Issue by hhb19900618** [waynezxcv/Gallop#3]
真机运行，我发现小图没显示之前  去点击空白区域 ，程序崩溃的

Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [160 nan]'

**Comment by waynezxcv** [comment]
你好，谢谢你的邮件！
应该是照片浏览器的问题……因为动画需要获取到图片在屏幕中的位置。
尽快修复，谢谢～


发自 网易邮箱大师
在2016年04月26日 14:32，testPublicProfile 写道:

真机运行，我发现小图没显示之前 去点击空白区域 ，程序崩溃的

Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [160 nan]'

**Comment by waynezxcv** [comment]
已修复。

**Comment by hhb19900618** [comment]
真佩服你能封装出这么复杂的代码，怎么做到的呢？？
