### ISSUE TITLE
内存会飙到很高

### ISSUE THREAD

**Issue by errorUserInfo** [waynezxcv/Gallop#34]

**Comment by waynezxcv** [comment]
用Instruments测试发现，内存占用过大，是SDWebImage 的[UIImage decodedImageWithImage]方法对图片解压缓存造成的。如图
![p](https://cloud.githubusercontent.com/assets/8408918/20893215/f5f3add8-bb4b-11e6-94ea-06b95c0800c0.png)
这里也有提到，https://github.com/rs/SDWebImage/issues/538
解决办法有：
1.减小图片分辨率
2.[[SDImageCache sharedImageCache] setShouldDecompressImages:NO];
[[SDWebImageDownloader sharedDownloader] setShouldDecompressImages:NO];设置为不解压图片
3.[[SDImageCache sharedImageCache] setMaxCacheSize:XXX];限制最大缓存大小。

以Demo为例，在iphone7上跑确实会占用到120M左右（内存2G），iphone6及之前机型应该是30M左右（内存1G）。

**Comment by waynezxcv** [comment]
![p](https://cloud.githubusercontent.com/assets/8408918/20893481/e5eb0854-bb4c-11e6-876b-5035052b0651.png)
那个图片太小了 - -

**Comment by errorUserInfo** [comment]
嗯 谢啦

**Comment by graceydb** [comment]
setShouldDecompressImages:NO 没作用呢，4.3.3版本，加载尺寸大点的图片内存还是会暴涨
