### ISSUE TITLE
点击再滑动后文字的高亮状态依然存在

### ISSUE THREAD

**Issue by errorUserInfo** [waynezxcv/Gallop#39]

**Comment by waynezxcv** [comment]
是长按么？如果是长按要手动用LWAsyncDiplayView的
/**
 *  移除高亮显示
 *
 */
- (void)removeHighlightIfNeed;
方法清除。

**Comment by errorUserInfo** [comment]
不是长按，是点击的瞬间再滑动就会出现

**Comment by waynezxcv** [comment]
建议更新版本。

**Comment by XYFGYC** [comment]
SDWebImage 您用的版本是 3.7 的 ，我项目中升级到3.8 之后有好多错误，是SDWebImage里面的方法改了，我改了一天也没改好，请问在不换SDWebImage版本的情况下，有什么更好的解决办法吗？

**Comment by waynezxcv** [comment]
@XYFGYC 已更新
