### ISSUE TITLE
LWImageItem中下载比较大的图片会导致CPU飙到很高导致崩溃，尤其使用LWProgeressHUD加载

### ISSUE THREAD

**Issue by errorUserInfo** [waynezxcv/Gallop#40]

**Comment by waynezxcv** [comment]
比较大的图片具体是多大的图片？那个图片浏览器不属于Gallop组件。
CPU彪很高不太可能吧...LWProgeressHUD只是个进度条，中间除了一个CAShaperLayer没别的了。应该不会有什么联系。
