### ISSUE TITLE
感觉跟YYText代码很像

### ISSUE THREAD

**Issue by nLoser** [waynezxcv/Gallop#44]
emoji显示不出来，用LWText不现实

**Comment by waynezxcv** [comment]
显示表情需要先将图片资源添加到工程并按相关命名规则命名，Demo中有演示示例。
你也可以自己写正则解析，原理是将需要替换的的文字用正则匹配出来，转换成表情图片的文件名，然后使用LWTextStorage的
『
- (void)lw_replaceTextWithImage:(UIImage *)image
                                    contentMode:(UIViewContentMode)contentMode
                                          imageSize:(CGSize)size
                                           alignment:(LWTextAttachAlignment)attachAlignment
』
方法将文字替换成图片。
