### ISSUE TITLE
放在UITableViewCell上刷新时有延迟

### ISSUE THREAD

**Issue by kevin19900204** [waynezxcv/Gallop#47]

**Comment by lceboy** [comment]
How to copy and paste

**Comment by waynezxcv** [comment]
由于渲染是异步执行的,所以会出现延迟.
1.可以在刷新前将displaysAsynchronously属性设为NO.使刷新过程不使用异步绘制,待刷新完毕后再讲displaysAsynchronously设为YES.
2.像Demo中那样截图覆盖.待刷新完毕后移除.
